# Generated by Django 5.1.4 on 2025-01-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_hydjobs_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
