# Generated by Django 5.1.4 on 2025-01-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_hydjobs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydjobs',
            name='company',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
